/* Explicit opt-in device regression, not part of the dependency-free host test.
 * Compile with a private coli_stream_fixture.h generated by pack_stream_fixture.py.
 * Replay each expert forward then backward to exercise both DMA buffer slots.
 * Input vectors are independent fixture cases, NOT transformer layers/tokens.
 */
#define _POSIX_C_SOURCE 200809L
#include "coli_npu_graph.h"
#include "coli_hexagon_engine.h"
#include "coli_npu_quant.h"
#include <errno.h>
#include <fcntl.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include "coli_stream_fixture.h"

#define MAT ((size_t)FIX_D * FIX_F * sizeof(uint16_t))
typedef struct {
    ColiNpuGraph *graph;
    ColiNpuBuf *weights[2], *x, *y;
    ColiNpuRegistration wr[2][3], xr, yr;
    Qnn_Tensor_t inputs[4], output;
    ColiHexagonJob jobs[2*FIX_N];
    float refs[FIX_V][FIX_N][FIX_D];
    uint16_t xs[FIX_V][FIX_D], previous[FIX_N][FIX_D];
    unsigned calls, numerical_failures, repeat_failures;
} Test;

static int read_exact(const char *path, void *p, size_t bytes) {
    FILE *f = fopen(path, "rb");
    int ok;
    if (!f) return errno;
    ok = fread(p, 1, bytes, f) == bytes && fgetc(f) == EOF && !ferror(f);
    fclose(f);
    return ok ? 0 : EIO;
}
static double now_ms(void) {
    struct timespec t;
    if (clock_gettime(CLOCK_MONOTONIC, &t)) return NAN;
    return t.tv_sec*1000.0 + t.tv_nsec*1e-6;
}
static void tensor(Qnn_Tensor_t *t, unsigned i) {
    t->version = QNN_TENSOR_VERSION_1;
    t->v1.id = fix_ids[i]; t->v1.name = fix_names[i];
    t->v1.type = i == FIX_Y ? QNN_TENSOR_TYPE_APP_READ : QNN_TENSOR_TYPE_APP_WRITE;
    t->v1.dataFormat = QNN_TENSOR_DATA_FORMAT_FLAT_BUFFER;
    t->v1.dataType = fix_types[i];
    t->v1.rank = 2; t->v1.dimensions = fix_dims[i];
    if (fix_types[i] == QNN_DATATYPE_FLOAT_16) {
        t->v1.quantizeParams.encodingDefinition = QNN_DEFINITION_UNDEFINED;
        t->v1.quantizeParams.quantizationEncoding = QNN_QUANTIZATION_ENCODING_UNDEFINED;
        return;
    }
    t->v1.quantizeParams.encodingDefinition = QNN_DEFINITION_DEFINED;
    t->v1.quantizeParams.quantizationEncoding = QNN_QUANTIZATION_ENCODING_SCALE_OFFSET;
    t->v1.quantizeParams.scaleOffsetEncoding.scale = fix_scales[i];
    t->v1.quantizeParams.scaleOffsetEncoding.offset = fix_offsets[i];
}
static int begin(void *u, uint64_t position) { (void)u; return position ? EINVAL : 0; }
static int route(void *u, uint32_t vector, const ColiHexagonJob **jobs, size_t *n) {
    Test *t = u;
    void *p;
    int e;
    if (vector >= FIX_V) return EINVAL;
    if ((e = coli_npu_buf_begin(t->x, 1, &p))) return e;
    memcpy(p, t->xs[vector], sizeof(t->xs[vector]));
    if ((e = coli_npu_buf_end(t->x))) return e;
    *jobs = t->jobs; *n = 2*FIX_N;
    return 0;
}
static int tail(void *u, uint32_t l) { (void)u; (void)l; return 0; }
static int prepare(void *u, const ColiHexagonJob *job, void *mapped, size_t capacity) {
    (void)u;
    return coli_npu_i4_f16_expand(mapped,job->bytes,capacity,(size_t)3*FIX_D*FIX_F);
}
static double decode(uint16_t bits) {
    unsigned exponent=(bits>>10)&31u, fraction=bits&1023u;
    double v;
    if (fix_types[FIX_Y] != QNN_DATATYPE_FLOAT_16)
        return ((double)bits+fix_offsets[FIX_Y])*fix_scales[FIX_Y];
    if (exponent == 31) v = fraction ? NAN : INFINITY;
    else if (!exponent) v = ldexp((double)fraction,-24);
    else v = ldexp((double)(1024+fraction),(int)exponent-25);
    return bits&32768u ? -v : v;
}
static int finish(void *u) {
    Test *t = u;
    printf("summary calls=%u expected=%u numerical_failures=%u repeat_failures=%u\n",
           t->calls, 2*FIX_N*FIX_V, t->numerical_failures, t->repeat_failures);
    return t->calls == 2*FIX_N*FIX_V && !t->numerical_failures && !t->repeat_failures ? 0 : EIO;
}
static int execute(void *u, uint32_t vector, const ColiHexagonJob *j,
                   ColiNpuBuf *b, unsigned slot) {
    Test *t = u;
    Qnn_ErrorHandle_t qe = 0;
    uint16_t *p;
    double dot=0, yy=0, rr=0, se=0, start, elapsed, cosine, l2;
    unsigned i, repeat = t->calls % (2*FIX_N) >= FIX_N;
    int e, unequal;
    if (slot > 1 || b != t->weights[slot] || j->expert >= FIX_N || vector >= FIX_V)
        return EINVAL;
    for (i=0; i<3; ++i)
        if ((e=coli_npu_qnn_bind(&t->inputs[fix_widx[i]], &t->wr[slot][i]))) return e;
    start = now_ms();
    e = coli_npu_graph_execute(t->graph, t->inputs, 4, &t->output, 1, &qe);
    elapsed = now_ms()-start;
    if (e) { fprintf(stderr,"graphExecute errno=%d QNN=%llu\n", e,(unsigned long long)qe); return e; }
    if ((e=coli_npu_buf_begin(t->y, 0, (void **)&p))) return e;
    for (i=0; i<FIX_D; ++i) {
        double y=decode(p[i]);
        double r=t->refs[vector][j->expert][i];
        dot+=y*r; yy+=y*y; rr+=r*r; se+=(y-r)*(y-r);
    }
    unequal = repeat && memcmp(t->previous[j->expert], p, sizeof(t->previous[0]));
    memcpy(t->previous[j->expert], p, sizeof(t->previous[0]));
    if ((e=coli_npu_buf_end(t->y))) return e;
    ++t->calls;
    cosine = dot/sqrt(yy*rr); l2 = sqrt(se/rr);
    if (!isfinite(cosine) || !isfinite(l2) || rr<=0 || yy<=0 || cosine<0.999 || l2>0.05)
        ++t->numerical_failures;
    if (unequal) ++t->repeat_failures;
    printf("vector=%u expert=%u slot=%u cosine=%.9f relative_L2=%.9f repeat=%u equal=%s graph_ms=%.3f\n",
           vector,j->expert,slot,cosine,l2,repeat,unequal?"false":"true",elapsed);
    return 0; /* Collect all errors; finish rejects the entire test. */
}
int main(int argc, char **argv) {
    Test *t = calloc(1, sizeof(*t));
    ColiHexagonEngine *engine = NULL;
    Qnn_ErrorHandle_t qe = 0;
    ColiHexagonOps ops = {begin,route,tail,execute,tail,finish,FIX_INT4?prepare:NULL};
    unsigned i,k;
    int e,rc=1,fd=-1;
    double start;
    setvbuf(stdout, NULL, _IOLBF, 0);
    if (!t) return 1;
    if (argc!=7) { fprintf(stderr,"usage: %s backend rpcmem graph weights.u16 x.u16 refs.f32\n",argv[0]); free(t); return 2; }
#define TRY(call) do { e=(call); if(e) { fprintf(stderr,"%s errno=%d QNN=%llu\n",#call,e,(unsigned long long)qe);goto done;} } while(0)
    TRY(read_exact(argv[5],t->xs,sizeof(t->xs)));
    TRY(read_exact(argv[6],t->refs,sizeof(t->refs)));
    TRY(coli_npu_graph_open(&t->graph,argv[1],argv[3],fix_graph,&qe));
    TRY(coli_npu_buf_rpcmem(&t->x,argv[2],sizeof(t->xs[0])));
    TRY(coli_npu_buf_rpcmem(&t->y,argv[2],sizeof(t->xs[0])));
    for(i=0;i<4;++i) tensor(&t->inputs[i],i);
    tensor(&t->output,FIX_Y);
    TRY(coli_npu_qnn_register(&t->xr,coli_npu_graph_api(t->graph),coli_npu_graph_context(t->graph),t->x,0,2,fix_dims[FIX_X],fix_types[FIX_X],&qe));
    TRY(coli_npu_qnn_register(&t->yr,coli_npu_graph_api(t->graph),coli_npu_graph_context(t->graph),t->y,0,2,fix_dims[FIX_Y],fix_types[FIX_Y],&qe));
    TRY(coli_npu_qnn_bind(&t->inputs[FIX_X],&t->xr));
    TRY(coli_npu_qnn_bind(&t->output,&t->yr));
    for(i=0;i<2;++i) {
        TRY(coli_npu_buf_rpcmem(&t->weights[i],argv[2],3*MAT));
        for(k=0;k<3;++k) TRY(coli_npu_qnn_register(&t->wr[i][k],coli_npu_graph_api(t->graph),coli_npu_graph_context(t->graph),t->weights[i],k*MAT,2,fix_dims[fix_widx[k]],fix_types[fix_widx[k]],&qe));
    }
    for(i=0;i<2*FIX_N;++i) {
        unsigned expert=i<FIX_N ? i : 2*FIX_N-1-i;
        t->jobs[i].offset=(uint64_t)expert*fix_encoded_bytes;
        t->jobs[i].bytes=fix_encoded_bytes; t->jobs[i].expert=expert; t->jobs[i].gate=1.0f/FIX_N;
    }
    fd=open(argv[4],O_RDONLY); if(fd<0) goto done;
    TRY(coli_hexagon_engine_create(&engine,fd,t->weights[0],t->weights[1],&ops,t));
    start=now_ms();
    TRY(coli_hexagon_token_step(engine,0,FIX_V));
    printf("pipeline_ms=%.3f encoded_bytes_per_expert=%zu storage_int4=%u\n",
           now_ms()-start,fix_encoded_bytes,(unsigned)FIX_INT4);
    rc=0;
done:
    coli_hexagon_engine_free(&engine); if(fd>=0) close(fd);
    for(i=0;i<2;++i) {
        for(k=0;k<3;++k) if(coli_npu_qnn_unregister(&t->wr[i][k],&qe)) return 1;
        if(coli_npu_buf_free(&t->weights[i])) return 1;
    }
    if(coli_npu_qnn_unregister(&t->xr,&qe) || coli_npu_qnn_unregister(&t->yr,&qe)) return 1;
    if(coli_npu_buf_free(&t->x) || coli_npu_buf_free(&t->y)) return 1;
    if(coli_npu_graph_close(&t->graph,&qe)) return 1;
    free(t);
    return rc;
}
